

'use client';

import { ThemeProvider } from 'next-themes';
import { Sevillana, Cairo } from 'next/font/google';
import './globals.css';
import Header from '../components/Header';
import Footer from '../components/Footer';

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const sevillana = Sevillana({ subsets: ['latin'], weight:['400'] });
const cairo = Cairo({subsets: ['arabic'] });

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={cairo.className} >
    <body className='bg-gray-700 text-white'>
    <ThemeProvider attribute='class' >
      <Header  />
      {children}
      <div className={sevillana.className}>
      <Footer />
      </div>
      </ThemeProvider>
    </body>
  </html>
  )
}
